config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('main.users.urls', namespace="users")),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.web.urls', namespace="web")),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/web/urls.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import gettext_lazy as _
from django.urls import path

from .views import *
from main.aydin.views import *
app_name = 'web'

urlpatterns = [
	path('manage/', global_manage, name='global_manage'),
	path('', HomeView.as_view(), name='welcome_view'),

	path('blog-list/', 				                               view=BlogView.as_view(),                     name='blog_view_en'),
	path('blog-detail/<slug:slug>/' ,                              view=BlogDetail.as_view(),                   name="blog_detail_en"),
	path('blog/', 			    		                           view=BlogTrView.as_view(),                   name='blog_view'),
	path('blog-detay/<slug:slug>/',                                view=BlogTrDetail.as_view(),                 name="blog_detail"),

	path('aydinlatma-metni/',                                      view=KvKKView.as_view(),                     name="aydinlatma_metni"),
	path('privacy-policy/',       		                           view=KvKKENView.as_view(),                   name="aydinlatma_metni_en"),
                        
	path('about/',                                                 view=AboutView.as_view(),                    name='about_en'),
	path('hakkimizda/',                                            view=AboutTRView.as_view(),                  name='about'),
	path('iletisim/',                                              view=IletisimSup.as_view(),                  name='contact'),
	path('contact/',                                               view=BecomeSupport.as_view(),                name='contact_en'),
	path('urun-kategorileri',                               view=ProductCategoryTrView.as_view(),         name='prod-cat'),
	path('ekibimiz',                               view=TeamsView.as_view(),         name='teams'),

	path('urun-kategorileri/<id>/',                               view=ProductCategoryDetailTrView.as_view(),         name='prod-cat-det'),
	path('ekibimiz/<id>/',                               view=TeamsDetailView.as_view(),         name='team-det'),

	path('urunler/',                     		                   view=ProductTrView.as_view(),                name='per_view'),
	path('urun-detay/<slug:slug>/',      		                   view=ProductDetailTrView.as_view(),          name='per_detail_view'),
	path('products/',                    		                   view=ProductView.as_view(),                  name='per_viewen'),
	path('product-detail/<slug:slug>/',  		                   view=ProductDetailENView.as_view(),          name='per_detail_viewen'),

	path('dis-ortam/cadde-aydinlatmasi/',                          view=ProductTrCaddBView.as_view(),           name='dis_cadde'),
	path('dis-ortam/lineer-ledtube-volans/',                       view=ProductTrLineerLedView.as_view(),       name='linner_led'),
	path('dis-ortam/projector/',                                   view=ProductTrProjectorView.as_view(),       name='projector'),
	path('dis-ortam/el-feneri/',                                   view=ProductTrElfeView.as_view(),            name='el-feneri'),
	path('dis-ortam/bahce-park-aydinlatmasi/',                     view=ProductTrParkView.as_view(),            name='park'),
	path('dis-ortam/wallwasher/',                                  view=ProductTrWallwasherView.as_view(),      name='wallwasher'),
	path('dis-ortam/mobil-isik-kulesi/',                           view=ProductTrMobisView.as_view(),           name='mobil-isik-kulesi'),
	path('dis-ortam/dot-led-scorpius/',                            view=ProductTrDotLedView.as_view(),          name='dot-led-scorpius'),
	path('dis-ortam/arac-ustu-isik-kulesi/',                       view=ProductTrAracUstuView.as_view(),        name='arac-ustu-isik-kulesi'),
	path('dis-ortam/portatif-alan-aydinlatmasi/',                  view=ProductTrPorTatifUFLEDView.as_view(),   name='ufled'),
	path('dis-ortam/moduler-led-aydinlatmas-seti/',                view=ProductTrYBTsedView.as_view(),          name='ybtsed'),
	path('dis-ortam/dekoratif-led-ampul/',                         view=ProductTrDekredampulView.as_view(),     name='dek-led-ampul'),
	path('dis-ortam/aksesuarlar/',                                 view=ProductTrAksesuarlarView.as_view(),     name='aksesuarlar'),

	path('outdoor-products/cadde-aydinlatmasi/',                          view=ProductCaddBView.as_view(),           name='dis_caddeen'),
	path('outdoor-products/lineer-ledtube-volans/',                       view=ProductLineerLedView.as_view(),       name='linner_leden'),
	path('outdoor-products/projector/',                                   view=ProductProjectorView.as_view(),       name='projectoren'),
	path('outdoor-products/el-feneri/',                                   view=ProductElfeView.as_view(),            name='el-fenerien'),
	path('outdoor-products/bahce-park-aydinlatmasi/',                     view=ProductParkView.as_view(),            name='parken'),
	path('outdoor-products/wallwasher/',                                  view=ProductWallwasherView.as_view(),      name='wallwasheren'),
	path('outdoor-products/mobil-isik-kulesi/',                           view=ProductMobisView.as_view(),           name='mobil-isik-kulesien'),
	path('outdoor-products/dot-led-scorpius/',                            view=ProductDotLedView.as_view(),          name='dot-led-scorpiusen'),
	path('outdoor-products/arac-ustu-isik-kulesi/',                       view=ProductAracUstuView.as_view(),        name='arac-ustu-isik-kulesien'),
	path('outdoor-products/portatif-alan-aydinlatmasi/',                  view=ProductPorTatifUFLEDView.as_view(),   name='ufleden'),
	path('outdoor-products/moduler-led-aydinlatmas-seti/',                view=ProductYBTsedView.as_view(),          name='ybtseden'),
	path('outdoor-products/dekoratif-led-ampul/',                         view=ProductDekredampulView.as_view(),     name='dek-led-ampulen'),
	path('outdoor-products/aksesuarlar/',                                 view=ProductAksesuarlarView.as_view(),     name='aksesuarlaren'),


	path('ic-ortam/dekoratif-led-ampul/',                          view=ProductTrDekredampulIcView.as_view(),   name='dek-led-ampul-ic'),
	path('ic-ortam/yuksek-tavan-led-aydinlatmasi/',                view=ProductTrYuksekTavansedView.as_view(),  name='yuk-tav-led'),
	path('ic-ortam/dekoratif-led-aydinlatma-seti/',                view=ProductTrDekoratifLedView.as_view(),    name='dek-led-ayd-seti'),

	path('indoor-products/dekoratif-led-ampul/',                          view=ProductDekredampulIcView.as_view(),   name='dek-led-ampul-icen'),
	path('indoor-products/yuksek-tavan-led-aydinlatmasi/',                view=ProductYuksekTavansedView.as_view(),  name='yuk-tav-leden'),
	path('indoor-products/dekoratif-led-aydinlatma-seti/',                view=ProductDekoratifLedView.as_view(),    name='dek-led-ayd-setien'),

	path('yardimci-urunler/cob-led-modül-armekeddon/',             view=ProductTrCobledView.as_view(),          name='cobled'),
	path('yardimci-urunler/waterproof-connectorler/',              view=ProductTrVaterProfConView.as_view(),    name='waterprof'),
	path('yardimci-urunler/waterproof-enerji-dagitici/',           view=ProductTrVaterProfEnerView.as_view(),   name='waterprofener'),

	path('auxiliary-products/cob-led-modül-armekeddon/',             view=ProductCobledView.as_view(),          name='cobleden'),
	path('auxiliary-products/waterproof-connectorler/',              view=ProductVaterProfConView.as_view(),    name='waterprofen'),
	path('auxiliary-products/waterproof-enerji-dagitici/',           view=ProductVaterProfEnerView.as_view(),   name='waterprofeneren'),

	path('galeri/',                                              view=ProjectsTRView.as_view(),               name='project'),
	path('proje-detay/<slug:slug>/',                               view=ProjectsDetailTrView.as_view(),         name='proje_detay'),
	

	path('projeler/spor-tesisleri/',                                view=ProjectsSportTRView.as_view(),         name='spor'),
	path('projeler/gayrimenkul-insaat/',                            view=ProjectsGayrTRView.as_view(),          name='gayin'),
	path('projeler/halka-acik-alanlar/',                            view=ProjectsHalkTRView.as_view(),          name='halac'),
	path('projeler/ozel-kurumlar/',                                 view=ProjectsOzkTRView.as_view(),           name='ozkur'),
	path('projeler/kamu-kurumlari/',                                view=ProjectsKamuTRView.as_view(),          name='kamu'),
	
	path('projects/',                             	                view=ProjectsView.as_view(),                name='projecten'),
	path('project-detail/<slug:slug>/',                             view=ProjectsDetailENView.as_view(),        name='project-detail'),

	path('projeler/sports-facilities/',                             view=ProjectsSportView.as_view(),           name='sporen'),
	path('projeler/real-estate-and-construction/',                  view=ProjectsGayrView.as_view(),            name='gayinen'),
	path('projeler/public-areas/',                             		view=ProjectsHalkView.as_view(),            name='halacen'),
	path('projeler/private-instituions/',                           view=ProjectsOzkView.as_view(),             name='ozkuren'),
	path('projeler/public-instituions/',                            view=ProjectsKamuView.as_view(),            name='kamuen'),

]

main/aydin/models/about.py
from __future__ import unicode_literals
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.conf import settings
from main.core.models import TimeStampedModel, Currency
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from .blog import *
class About(TimeStampedModel):
    class Meta:
        verbose_name = _("EN Hakkımızda")
        verbose_name_plural = _("EN Hakkımızda")
        ordering = ("-created",)
    title  = models.CharField(_("Title"), max_length=200,blank=True,null=True)
    body   = RichTextUploadingField(_("About Body"), blank=True)
    image  = models.ImageField(_("About Image"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True, default=settings.DEFAULT_BLOG_IMAGE)
    slug = models.SlugField(max_length=100)
    titlesite = models.CharField(_("Site Title"), max_length=200,blank=True, null=True)
    description = models.CharField(_("Meta Description"), max_length=200,blank=True, null=True)
    keywords =  models.ManyToManyField(Keywords, verbose_name=_("Keywords"),blank=True, null=True)

    def __str__(self):
        return self.title

    def get_dict(self):
        return dict(
            pk    = self.pk,
            title = self.title,
            body  = self.body,
            image = self.image,
            slug  = self.slug,

        )
class AboutTR(TimeStampedModel):
    class Meta:
        verbose_name = _("4-Hakkımızda ")
        verbose_name_plural = _("4-Hakkımızda")
        ordering = ("-created",)
    title  = models.CharField(_("Başlık"), max_length=200,blank=True,null=True)
    body   = RichTextUploadingField(_("Hakkımızda Body"), blank=True)
    image  = models.ImageField(_("Hakkımızda Resim"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True, default=settings.DEFAULT_BLOG_IMAGE)
    titlesite = models.CharField(_("Site Başlık"), max_length=200,blank=True, null=True)
    description = models.CharField(_("Meta Açıklama"), max_length=200,blank=True, null=True)
    keywords =  models.ManyToManyField(KeywordsTR, verbose_name=_("Keywords"),blank=True, null=True)
    def __str__(self):
        return self.title

    def get_dict(self):
        return dict(
            pk    = self.pk,
            title = self.title,
            body  = self.body,
            image = self.image,
            slug  = self.slug,
        )

main/aydin/views/about.py
from django.shortcuts import render,redirect
from django.views import View
from django.shortcuts import get_object_or_404
from main.core.utils import get_query,paginate
from main.aydin.models import *


class AboutView(View):
    template_name= "web/pages/about.html"
    ctx = {}
    def get(self, request, *args, **kwargs):
        about = About.objects.first()
        if request.LANGUAGE_CODE == 'tr' :
            return redirect('web:about')
        self.ctx = {
            'about' : about,
        }
        return render(request, self.template_name, self.ctx)
    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, self.ctx)


class AboutTRView(View):
    template_name= "web/pages/about_tr.html"
    ctx = {}
    def get(self, request, *args, **kwargs):
        about = AboutTR.objects.first()
        self.ctx = {
            'about' : about,
        }
        return render(request, self.template_name, self.ctx)
    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, self.ctx)

main/aydin/views/contact.py
from django.shortcuts import render,redirect
from django.views import View
from django.core.mail import EmailMultiAlternatives
from main.aydin.forms import SupportForm
from main.aydin.models import *
from django.contrib import messages
from django.utils.html import strip_tags

from django.template.loader import render_to_string
class BecomeSupport(View):
    template_name = "web/pages/contact.html"
    ctx = {}
    def get(self, request, *args, **kwargs):
        cont = İletisimSeo.objects.first()
        if request.LANGUAGE_CODE == 'tr' :
            return redirect('web:contact')
        self.ctx ={
            'cont':cont,
        }
        return render(request, self.template_name,self.ctx)
    def post(self,request, *args, **kwargs):
        form = SupportForm()
        full_name = request.POST.get("full_name",None)
        email         = request.POST.get("email", None)
        body           = request.POST.get("body", None)
        tel           = request.POST.get("tel", None)

        form.is_valid()
        obj = Support.objects.create(
            full_name = full_name or "Untitled Partner Name",
            email = email,
            body = body,
            tel = tel,
        )
        obj.save()

        resstatus, resmessage = 200, ("Your contact request has been created successfully. ")
        if resstatus == 200:
            messages.success(request, ("Your contact request has been created successfully."))
        self.ctx = {
            'full_name' : full_name,
            'email'         : email,
            'body'           : body,
            'tel'       : tel,
        }
        return render(request, self.template_name, self.ctx)

class IletisimSup(View):
    template_name = "web/pages/iletisim.html"
    ctx = {}
    def get(self, request, *args, **kwargs):
        cont = İletisimSeoTR.objects.first()

        self.ctx ={
            'cont':cont,
        }
        return render(request, self.template_name,self.ctx)
    def post(self,request, *args, **kwargs):
        form = SupportForm()
        full_name = request.POST.get("full_name",None)
        email         = request.POST.get("email", None)
        body           = request.POST.get("body", None)
        tel           = request.POST.get("tel", None)

        form.is_valid()
        obj = Support.objects.create(
            full_name = full_name or "Untitled Partner Name",
            email = email,
            body = body,
            tel = tel,
        )
        obj.save()
        resstatus, resmessage = 200, ("İletişim Taleniniz alındı.")
        if resstatus == 200:
            messages.success(request, ("İletişim Taleniniz alındı."))

        self.ctx = {
            'full_name' : full_name,
            'email'         : email,
            'body'           : body,
            'tel'       : tel,
        }
        return render(request, self.template_name, self.ctx)

main/web/templates/web/pages/product-cat-tr-detail.html
{% extends "web/base.html" %}
{% load static i18n %}
{% block title %}{% trans "ÜRÜNLERİMİZ" %}{% endblock title %}
{% block extracss %}

{% endblock extracss %}
{% block content %}
    <!--Page Title-->
    <section class="page-title" style="background-image:url('{{STATIC_URL}}web/images/background/8.jpg');">
    	<div class="auto-container">
        	<div class="inner-box">
                <h1>Ürünler</h1>
                <ul class="bread-crumb">
                	<li><a href="{% url 'web:welcome_view' %}">Ana Sayfa</a></li>
                    <li>Ürünler</li>
                    <li>{{category.name}}</li>

                </ul>
            </div>
        </div>
    </section>
    <!--End Page Title-->
    
    <!--Shop Section-->
    <section class="shop-section">
    	<div class="auto-container">
        	<!--Filter Bar-->
        	<div class="filter-bar clearfix">
            	<div class="title pull-left">{{category.name}}  Kategori Ürünlerimiz</div>
                <div class="filters pull-right">
                
                	
             
                    <!-- Search Form -->
                  
                    
                </div>
            </div>
            
            <div class="row clearfix">
            	

                {% for prod in  protrlist %}
                <!--Shop Item-->
                <div class="shop-item col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box">
                        <div class="image-box"><img style="max-height: 450px;min-height: 450px;" src="{{prod.image.url}}" alt="">
                            <div class="overlay-box">
                                <!--lower box-->
                                <div class="lower-box">
                                    <h3><a href="{% url 'web:per_detail_view' prod.slug %}">{{prod.title}}</a></h3>
                                    <span class="price">{{prod.fiyat}} ₺  </span>
                                    <a href="{% url 'web:per_detail_view' prod.slug %}" class="theme-btn btn-style-one">&ensp;Detay</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                {% endfor %}        

            </div>
            
            <!-- Styled Pagination -->
            {% include 'web/includes/paginate.html' with page_obj=protrlist %}

            
        </div>
    </section>
    <!--End Shop Section-->
{% endblock content %}
{% block extrajs %}

{% endblock extrajs %}

main/web/templates/web/pages/product-tr-detail.html
{% extends "web/base.html" %}
{% load static i18n %}
{% load embed_video_tags %}
{% block title %}{{pro.title|upper}}{% endblock title %}
{% block extracss %}{% endblock extracss %}
{% block content %}

    <!--Page Title-->
    <section class="page-title" style="background-image:url('{{STATIC_URL}}web/images/background/8.jpg');">
    	<div class="auto-container">
        	<div class="inner-box">
                <h1>Ürün Detay</h1>
                <ul class="bread-crumb">
                	<li><a href="{% url 'web:welcome_view' %}">Ana Sayfa</a></li>
                    <li>{{pro.title}}</li>
                </ul>
            </div>
        </div>
    </section>
    <!--End Page Title-->
    
    <!--Shop Single-->
    <div class="shop-single">
        <div class="auto-container">
            <div class="row clearfix">
				
                <!--Content Side-->
                <div class="content-side col-lg-12 col-md-12 col-sm-12 col-xs-12">
                	<!--Product Details-->
                    <div class="product-details">
						
                        <!--Basic Details-->
                        <div class="basic-details">
                            <div class="row clearfix">
                                <div class="image-column col-md-5 col-sm-5 col-xs-12">
                                    <figure class="image-box"><a href="{{pro.image.urls}}" class="lightbox-image" title="Image Caption Here"><img src="{{pro.image.url}}" alt=""></a></figure>
                                </div>
                                <div class="info-column col-md-7 col-sm-7 col-xs-12">
                                    <div class="details-header">
                                        <h4>{{pro.title}}</h4>
                                        <div class="rating">
                                            <span class="fa fa-star-o"></span>
                                            <span class="fa fa-star-o"></span>
                                            <span class="fa fa-star-o"></span>
                                            <span class="fa fa-star-o"></span>
                                            <span class="fa fa-star-o"></span>
                                        </div>
                                        <div class="item-price">{{pro.fiyat}} ₺</div>
                                    </div>
                                    <div class="text">
                                        {{pro.body | safe}}
                                    </div>
                                    <div class="clearfix">
                                        <a href="https://api.whatsapp.com/send?phone=905300944114&text=Selamlar, {{pro.kod}} ürünüzle ilgili bilgi almak istiyorum" class="theme-btn btn-style-one "> Bize Yazın</a>
                                    </div>
                                 
                                </div>
                            </div>
                        </div>
                        <!--Basic Details-->
                        
                        <!--Product Info Tabs-->
                        <div class="product-info-tabs">
                            
                            <!--Product Tabs-->
                            <div class="prod-tabs tabs-box" id="product-tabs">
                            
                                <!--Tab Btns-->
                                <ul class="tab-btns tab-buttons clearfix">
                                    <li data-tab="#prod-description" class="tab-btn active-btn">Ürün Hakkında</li>
                                </ul>
                                
                                <!--Tabs Content-->
                                <div class="tabs-container tabs-content">
                                    
                                    <!--Tab / Active Tab-->
                                    <div class="tab active-tab" id="prod-description">
                                        <div class="content">
                                            <p> {{pro.tek_body|safe }}</p>
                                        </div>
                                    </div>
                                  
                                    
                                </div>
                                
                            </div>
                            
                        </div>
                        <!--End Product Info Tabs-->
                        
                        <!--Related Products-->
                        <div class="related-products">
                        	<h2>Benzer Ürünler</h2>
                            
                            <div class="row clearfix">
                            	<!--Shop Item-->
                                {% for prod in products  %}
                                <div class="shop-item col-lg-4 col-md-6 col-sm-6 col-xs-12">
                                    <div class="inner-box">
                                        <div class="image-box"><img style="max-height: 450px;min-height: 450px;" src="{{prod.image.url}}" alt="">
                                            <div class="overlay-box">
                                                <!--lower box-->
                                                <div class="lower-box">
                                                    <h3><a href="{% url 'web:per_detail_view' prod.slug %}">{{prod.title}}</a></h3>
                                                    <span class="price">{{prod.fiyat}} ₺ </span>
                                                    <a href="{% url 'web:per_detail_view' prod.slug %}" class="theme-btn btn-style-one">Detay</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %} 
                               
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
                <!--End Content Side-->
                
                <!--Sidebar-->
            
                <!--End Sidebar-->
            </div>
        </div>
    </div>
    <!--End Shop Single-->


{% endblock content %}
{% block extrajs %}{% endblock extrajs %}

main/web/templates/web/pages/projects-tr.html
{% extends "web/base.html" %}
{% load static i18n %}
{% block title %}{{blog_ic.titlesite}}{% endblock title %}
{% block meta %}
<meta name="description" content="{{blog_ic.description}}">
<meta name="keywords" content="{% for cer in blog_ic.keywords.all %}{{cer.name}},{% endfor %}">
{% endblock meta %}
{% block extracss %}{% endblock extracss %}
{% block content %}
<div class="page-content">
        
            <!-- INNER PAGE BANNER -->
            <div class="wt-bnr-inr overlay-wraper" style="background-image:url({{STATIC_URL}}web/images/projelerimiz.jpg);">
            	<div class="overlay-main bg-black opacity-07"></div>
                <div class="container">
                    <div class="wt-bnr-inr-entry">
                        <h1 class="text-white">Projelerimiz</h1>
                    </div>
                </div>
            </div>
            <!-- INNER PAGE BANNER END -->
            
            <!-- BREADCRUMB ROW -->                            
            <div class="bg-gray-light p-tb20">
            	<div class="container">
                    <ul class="wt-breadcrumb breadcrumb-style-2">
                        <li><a href="javascript:void(0);"><i class="fa fa-home"></i> Home</a></li>
                        <li>Projelerimiz</li>
                    </ul>
                </div>
            </div>
            <!-- BREADCRUMB ROW END -->
            
            <!-- SECTION CONTENT START -->
            <div class="section-full p-t80 p-b50">
                <div class="container">
                  <div class="section-head text-center">
                <h2 class="text-uppercase">AYDINLATMA PROJELERİMİZ</h2>
                <div class="wt-separator-outer">
                    <div class="wt-separator style-square">
                        <span class="separator-left bg-primary"></span>
                        <span class="separator-right bg-primary"></span>
                    </div>
                </div>
                <p>Spor Tesisleri, fuar alanları, kongre merkezleri, şehir parkları, inşaat ve daha birçok alanda gerçekleştirdiğimiz tüm projelerimiz burada!</p>
            </div>   
                	<!-- PAGINATION START -->
                    <div class="filter-wrap p-tb15">
                        <ul class="masonry-filter link-style  text-uppercase">
                            <li class="active"><a href="{% url 'web:project' %}">Tümü</a></li>
                            <li class=""><a href="{% url 'web:kamu' %}">KAMU KURUMLARI</a></li>
                            <li class=""><a href="{% url 'web:ozkur' %}">ÖZEL KURUMLAR</a></li>
                            <li class=""><a href="{% url 'web:halac' %}">HALKA AÇIK ALANLAR</a></li>
                            <li class=""><a href="{% url 'web:gayin' %}">GAYRİMENKUL VE İNŞAAT</a></li>
                            <li class=""><a href="{% url 'web:spor' %}">SPOR TESİSLERİ</a></li>
                        </ul>
                    </div>
                    <!-- PAGINATION END -->
                    
                    <!-- GALLERY START -->
                    <div class="row">
                        <div class="portfolio-wrap mfp-gallery" style="position: relative; height: 451.094px;">
                        {% for pro in proj  %}
                    		<!-- COLUMNS 1 -->
                           <div class="post masonry-item col-lg-4 col-md-6 col-sm-6 col-xs-12" >
                                <div class="blog-post blog-grid date-style-3">
                                    <div class="wt-post-media wt-img-effect zoom-slow">
                                        <a href="{% url 'web:proje_detay' pro.slug %}"><img src="{{pro.image.url}}" alt=""></a>
                                    </div>
                                    <div class="wt-post-info p-tb30 p-m30">
                                        <div class="wt-post-title ">
                                            <h3 class="post-title"><a href="#">{{pro.title}}</a></h3>
                                        </div>
                                        <div class="wt-post-text">
                                            <p>{{pro.body|safe|truncatechars:50}}</p> 
                                        </div>
                                        <div class="clearfix">
                                    <div class="wt-post-readmore pull-left">
                                         <a href="{% url 'web:proje_detay' pro.slug %}" title="READ MORE" rel="bookmark" class="site-button-link">Detay</a>
                                    </div>
                                </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                    <!-- GALLERY END -->
                </div>
            </div>
            <!-- SECTION CONTENT END  -->

        </div>
                {% include 'web/includes/contacttr.html' %}

{% endblock content %}
{% block extrajs %}{% endblock extrajs %}