config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('main.users.urls', namespace="users")),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.web.urls', namespace="web")),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/web/urls.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import gettext_lazy as _
from django.urls import path

from .views import *
from main.aydin.views import *
app_name = 'web'

urlpatterns = [
	path('manage/', global_manage, name='global_manage'),
	path('', HomeView.as_view(), name='welcome_view'),

	path('blog-list/', 				                               view=BlogView.as_view(),                     name='blog_view_en'),
	path('blog-detail/<slug:slug>/' ,                              view=BlogDetail.as_view(),                   name="blog_detail_en"),
	path('blog/', 			    		                           view=BlogTrView.as_view(),                   name='blog_view'),
	path('blog-detay/<slug:slug>/',                                view=BlogTrDetail.as_view(),                 name="blog_detail"),

	path('aydinlatma-metni/',                                      view=KvKKView.as_view(),                     name="aydinlatma_metni"),
	path('privacy-policy/',       		                           view=KvKKENView.as_view(),                   name="aydinlatma_metni_en"),
                        
	path('about/',                                                 view=AboutView.as_view(),                    name='about_en'),
	path('hakkimizda/',                                            view=AboutTRView.as_view(),                  name='about'),
	path('iletisim/',                                              view=IletisimSup.as_view(),                  name='contact'),
	path('contact/',                                               view=BecomeSupport.as_view(),                name='contact_en'),
	path('urun-kategorileri',                               view=ProductCategoryTrView.as_view(),         name='prod-cat'),
	path('ekibimiz',                               view=TeamsView.as_view(),         name='teams'),

	path('urun-kategorileri/<id>/',                               view=ProductCategoryDetailTrView.as_view(),         name='prod-cat-det'),
	path('ekibimiz/<id>/',                               view=TeamsDetailView.as_view(),         name='team-det'),

	path('urunler/',                     		                   view=ProductTrView.as_view(),                name='per_view'),
	path('urun-detay/<slug:slug>/',      		                   view=ProductDetailTrView.as_view(),          name='per_detail_view'),
	path('products/',                    		                   view=ProductView.as_view(),                  name='per_viewen'),
	path('product-detail/<slug:slug>/',  		                   view=ProductDetailENView.as_view(),          name='per_detail_viewen'),

	path('dis-ortam/cadde-aydinlatmasi/',                          view=ProductTrCaddBView.as_view(),           name='dis_cadde'),
	path('dis-ortam/lineer-ledtube-volans/',                       view=ProductTrLineerLedView.as_view(),       name='linner_led'),
	path('dis-ortam/projector/',                                   view=ProductTrProjectorView.as_view(),       name='projector'),
	path('dis-ortam/el-feneri/',                                   view=ProductTrElfeView.as_view(),            name='el-feneri'),
	path('dis-ortam/bahce-park-aydinlatmasi/',                     view=ProductTrParkView.as_view(),            name='park'),
	path('dis-ortam/wallwasher/',                                  view=ProductTrWallwasherView.as_view(),      name='wallwasher'),
	path('dis-ortam/mobil-isik-kulesi/',                           view=ProductTrMobisView.as_view(),           name='mobil-isik-kulesi'),
	path('dis-ortam/dot-led-scorpius/',                            view=ProductTrDotLedView.as_view(),          name='dot-led-scorpius'),
	path('dis-ortam/arac-ustu-isik-kulesi/',                       view=ProductTrAracUstuView.as_view(),        name='arac-ustu-isik-kulesi'),
	path('dis-ortam/portatif-alan-aydinlatmasi/',                  view=ProductTrPorTatifUFLEDView.as_view(),   name='ufled'),
	path('dis-ortam/moduler-led-aydinlatmas-seti/',                view=ProductTrYBTsedView.as_view(),          name='ybtsed'),
	path('dis-ortam/dekoratif-led-ampul/',                         view=ProductTrDekredampulView.as_view(),     name='dek-led-ampul'),
	path('dis-ortam/aksesuarlar/',                                 view=ProductTrAksesuarlarView.as_view(),     name='aksesuarlar'),

	path('outdoor-products/cadde-aydinlatmasi/',                          view=ProductCaddBView.as_view(),           name='dis_caddeen'),
	path('outdoor-products/lineer-ledtube-volans/',                       view=ProductLineerLedView.as_view(),       name='linner_leden'),
	path('outdoor-products/projector/',                                   view=ProductProjectorView.as_view(),       name='projectoren'),
	path('outdoor-products/el-feneri/',                                   view=ProductElfeView.as_view(),            name='el-fenerien'),
	path('outdoor-products/bahce-park-aydinlatmasi/',                     view=ProductParkView.as_view(),            name='parken'),
	path('outdoor-products/wallwasher/',                                  view=ProductWallwasherView.as_view(),      name='wallwasheren'),
	path('outdoor-products/mobil-isik-kulesi/',                           view=ProductMobisView.as_view(),           name='mobil-isik-kulesien'),
	path('outdoor-products/dot-led-scorpius/',                            view=ProductDotLedView.as_view(),          name='dot-led-scorpiusen'),
	path('outdoor-products/arac-ustu-isik-kulesi/',                       view=ProductAracUstuView.as_view(),        name='arac-ustu-isik-kulesien'),
	path('outdoor-products/portatif-alan-aydinlatmasi/',                  view=ProductPorTatifUFLEDView.as_view(),   name='ufleden'),
	path('outdoor-products/moduler-led-aydinlatmas-seti/',                view=ProductYBTsedView.as_view(),          name='ybtseden'),
	path('outdoor-products/dekoratif-led-ampul/',                         view=ProductDekredampulView.as_view(),     name='dek-led-ampulen'),
	path('outdoor-products/aksesuarlar/',                                 view=ProductAksesuarlarView.as_view(),     name='aksesuarlaren'),


	path('ic-ortam/dekoratif-led-ampul/',                          view=ProductTrDekredampulIcView.as_view(),   name='dek-led-ampul-ic'),
	path('ic-ortam/yuksek-tavan-led-aydinlatmasi/',                view=ProductTrYuksekTavansedView.as_view(),  name='yuk-tav-led'),
	path('ic-ortam/dekoratif-led-aydinlatma-seti/',                view=ProductTrDekoratifLedView.as_view(),    name='dek-led-ayd-seti'),

	path('indoor-products/dekoratif-led-ampul/',                          view=ProductDekredampulIcView.as_view(),   name='dek-led-ampul-icen'),
	path('indoor-products/yuksek-tavan-led-aydinlatmasi/',                view=ProductYuksekTavansedView.as_view(),  name='yuk-tav-leden'),
	path('indoor-products/dekoratif-led-aydinlatma-seti/',                view=ProductDekoratifLedView.as_view(),    name='dek-led-ayd-setien'),

	path('yardimci-urunler/cob-led-modül-armekeddon/',             view=ProductTrCobledView.as_view(),          name='cobled'),
	path('yardimci-urunler/waterproof-connectorler/',              view=ProductTrVaterProfConView.as_view(),    name='waterprof'),
	path('yardimci-urunler/waterproof-enerji-dagitici/',           view=ProductTrVaterProfEnerView.as_view(),   name='waterprofener'),

	path('auxiliary-products/cob-led-modül-armekeddon/',             view=ProductCobledView.as_view(),          name='cobleden'),
	path('auxiliary-products/waterproof-connectorler/',              view=ProductVaterProfConView.as_view(),    name='waterprofen'),
	path('auxiliary-products/waterproof-enerji-dagitici/',           view=ProductVaterProfEnerView.as_view(),   name='waterprofeneren'),

	path('galeri/',                                              view=ProjectsTRView.as_view(),               name='project'),
	path('proje-detay/<slug:slug>/',                               view=ProjectsDetailTrView.as_view(),         name='proje_detay'),
	

	path('projeler/spor-tesisleri/',                                view=ProjectsSportTRView.as_view(),         name='spor'),
	path('projeler/gayrimenkul-insaat/',                            view=ProjectsGayrTRView.as_view(),          name='gayin'),
	path('projeler/halka-acik-alanlar/',                            view=ProjectsHalkTRView.as_view(),          name='halac'),
	path('projeler/ozel-kurumlar/',                                 view=ProjectsOzkTRView.as_view(),           name='ozkur'),
	path('projeler/kamu-kurumlari/',                                view=ProjectsKamuTRView.as_view(),          name='kamu'),
	
	path('projects/',                             	                view=ProjectsView.as_view(),                name='projecten'),
	path('project-detail/<slug:slug>/',                             view=ProjectsDetailENView.as_view(),        name='project-detail'),

	path('projeler/sports-facilities/',                             view=ProjectsSportView.as_view(),           name='sporen'),
	path('projeler/real-estate-and-construction/',                  view=ProjectsGayrView.as_view(),            name='gayinen'),
	path('projeler/public-areas/',                             		view=ProjectsHalkView.as_view(),            name='halacen'),
	path('projeler/private-instituions/',                           view=ProjectsOzkView.as_view(),             name='ozkuren'),
	path('projeler/public-instituions/',                            view=ProjectsKamuView.as_view(),            name='kamuen'),

]

main/aydin/models/products.py
 
from __future__ import unicode_literals
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.conf import settings
from main.core.models import TimeStampedModel, Currency
from autoslug import AutoSlugField
from embed_video.fields import EmbedVideoField
from ckeditor_uploader.fields import RichTextUploadingField
from main.aydin.models.blog import *
class CertificaEN(TimeStampedModel):
    class Meta:
        verbose_name = _("EN Sertifika")
        verbose_name_plural = _("EN Sertifikalar")
        ordering = ("-created",)
    
    name    = models.CharField(_("Başlık"), max_length=200,)
    body     = models.FileField(_("Sertifika"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True)
    
    def __str__(self):
        return self.name
class BrosEN(TimeStampedModel):
    class Meta: 
        verbose_name = _("EN Broşür")
        verbose_name_plural = _("EN Broşürler")
        ordering = ("-created",)
    name    = models.CharField(_("Başlık"), max_length=200,)
    body     = models.FileField(_("Broşür"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True)
    def __str__(self):
        return self.name
class KlavuzEN(TimeStampedModel):
    class Meta: 
        verbose_name = _("EN Kullanım Klavuzu")
        verbose_name_plural = _("EN Kullanım Klavuzları")
        ordering = ("-created",)
    name    = models.CharField(_("Başlık"), max_length=200,)
    body     = models.FileField(_("Kullanım Klavuzu"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True)
    def __str__(self):
        return self.name
class ProductSlider(TimeStampedModel):
    class Meta: 
        verbose_name = "Ürün Slider"
        verbose_name_plural = "Ürün Sliderları"
    name  = models.CharField(_("Slider İsim"), max_length=200,)
    image = models.ImageField(_("Ürün Resim"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True, default=settings.DEFAULT_BLOG_IMAGE)
    def __str__(self):
        return self.name
class ProductCategory(TimeStampedModel):
    class Meta:
        verbose_name = _("EN Ürünler Alt Categori")
        verbose_name_plural = _("EN Ürünler Alt Categori ")
        ordering = ("-created",)
    name = models.CharField(_("Categori İsmi"), max_length=200,)
    #parent_category = models.ForeignKey(SubCategoryTR, null=True, blank=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.name
class Products(TimeStampedModel):
    class Meta:
        verbose_name = _("EN Ürün")
        verbose_name_plural = _("EN Ürünler ")
        ordering = ("-created",)
    DIS        = "DIŞ ORTAM"
    IC         = "İÇ ORTAM"
    YRD         = "YARDIMCI ÜRÜNLER"
    CATEGORY = (
        (DIS        , _("DIŞ ORTAM")),
        (IC   , _("İÇ ORTAM")),
        (YRD         , _("YARDIMCI ÜRÜNLER")),
    )
    title    = models.CharField(_("Başlık"), max_length=200,)
    body     = models.TextField(_("Ürün Yazı"), blank=True)
    image    = models.ImageField(_("Ürün Resim"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True, default=settings.DEFAULT_BLOG_IMAGE)
    slider    = models.ManyToManyField(ProductSlider, verbose_name=_("Ürün Slider"),blank=True, null=True)
    tek_body   = RichTextUploadingField(_("Teknik Özellikler"), blank=True)
    category = models.CharField(_("Kategori Seçiniz"),choices=CATEGORY, default=DIS, max_length=500)
    subcategory = models.ForeignKey(ProductCategory, verbose_name=_("Alt Kategori"),blank=True,null=True,on_delete=models.CASCADE)
    dowloads   = models.ForeignKey(KlavuzEN, verbose_name=_("Dökümanlar"),blank=True,null=True,on_delete=models.CASCADE)
    kod    = models.CharField(_("Ürün Kodu"), max_length=200,blank=True, null=True,)
    video   = EmbedVideoField(blank=True) 
    slug   = models.SlugField(max_length=100)
    titlesite = models.CharField(_("Site Title"), max_length=200,blank=True, null=True)
    description = models.CharField(_("Meta Description"), max_length=200,blank=True, null=True)
    keywords =  models.ManyToManyField(Keywords, verbose_name=_("Keywords"),blank=True, null=True)

    def __str__(self):
        return self.title


class Certifica(TimeStampedModel):
    verbose_name = _("TR Sertifika")
    verbose_name_plural = _("TR Sertifikalar")
    ordering = ("-created",)
    
    name    = models.CharField(_("Başlık"), max_length=200,)
    body     = models.FileField(_("Sertifika"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True)
    
    def __str__(self):
        return self.name
class Bros(TimeStampedModel):
    class Meta:
        verbose_name = _("TR Broşür")
        verbose_name_plural = _("TR Broşürler")
        ordering = ("-created",)
    name    = models.CharField(_("Başlık"), max_length=200,)
    body     = models.FileField(_("Broşür"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True)
    def __str__(self):
        return self.name
class Klavuz(TimeStampedModel):
    verbose_name = _("TR Kullanım Klavuzu")
    verbose_name_plural = _("TR Kullanım Klavuzları")
    ordering = ("-created",)
    name    = models.CharField(_("Başlık"), max_length=200,)
    body     = models.FileField(_("Kullanım Klavuzu"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True)
    def __str__(self):
        return self.name
class ProductCategoryTR(TimeStampedModel):
    class Meta:
        verbose_name = _(" 1.1-Ürünler  Kategori")
        verbose_name_plural = _("1.1-Ürünler Kategori ")
        ordering = ("ordering",)
    name = models.CharField(_("Categori İsmi"), max_length=200,)
    description = RichTextUploadingField(_(" Açıklama"),blank=True, null=True)
    ordering = models.PositiveIntegerField(null=True, blank=True, default=1)
    image    = models.ImageField(_(" Resim"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True, default=settings.DEFAULT_BLOG_IMAGE)


    def __str__(self):
        return self.name
    

class Teams(TimeStampedModel):
    class Meta:
        verbose_name = _(" 6-Ekibimiz")
        verbose_name_plural = _("6- Ekibimiz")
        ordering = ("ordering",)
    name = models.CharField(_("İsim"), max_length=200,)
    name1 = models.CharField(_("Görevi"), max_length=200,)
    image    = models.ImageField(_(" Resim"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True, default=settings.DEFAULT_BLOG_IMAGE)
    description = RichTextUploadingField(_("Detaylı Bilgi"),blank=True, null=True)
    ordering = models.PositiveIntegerField(null=True, blank=True, default=1)


    def __str__(self):
        return self.name
    
class ProductsTr(TimeStampedModel):
    class Meta:
        verbose_name = _("1-Ürün ")
        verbose_name_plural = _("1-Ürünler")
        ordering = ("-created",)

    title    = models.CharField(_("Başlık"), max_length=200,)
    body     = RichTextUploadingField(_("Ürün Yazı"), blank=True)
    image    = models.ImageField(_("Ürün Resim"), upload_to=settings.DEFAULT_BLOG_FOLDER, blank=True, default=settings.DEFAULT_BLOG_IMAGE)
    #slider    = models.ManyToManyField(ProductSlider, verbose_name=_("Ürün Slider"),blank=True, null=True)
    tek_body   = RichTextUploadingField(_("Teknik Özellikler"), blank=True)
    subcategory = models.ForeignKey(ProductCategoryTR, verbose_name=_(" Kategori"),blank=True,null=True,on_delete=models.CASCADE)
    kod    = models.CharField(_("Ürün Kodu"), max_length=200,blank=True, null=True,)
    slug   = models.SlugField(max_length=100)
    titlesite = models.CharField(_("Site Title"), max_length=200,blank=True, null=True)
    description = models.CharField(_("Meta Description"), max_length=200,blank=True, null=True)
    keywords =  models.ManyToManyField(KeywordsTR, verbose_name=_("Keywords"),blank=True, null=True)
    fiyat    = models.CharField(_("Fiyat"), max_length=200, blank=True, null=True)

    def __str__(self):
        return self.title

main/web/templates/web/pages/products/aksesuarlar.html
{% extends "web/base.html" %}
{% load static i18n %}
{% block title %}{% trans "SAMPLE" %}{% endblock title %}
{% block extracss %}
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/aside.css' %}">

{% endblock extracss %}
{% block content %}
<div class="page-content">
        
            <!-- INNER PAGE BANNER -->
            <div class="wt-bnr-inr overlay-wraper" style="background-image:url({{STATIC_URL}}web/images/urunlerimiz.jpg);">
            	<div class="overlay-main bg-black opacity-07"></div>
                <div class="container">
                    <div class="wt-bnr-inr-entry">
                        <h1 class="text-white">ÜRÜNLERİMİZ</h1>
                    </div>
                </div>
            </div>
            <!-- INNER PAGE BANNER END -->
            
            <!-- BREADCRUMB ROW -->                            
            <div class="bg-gray-light p-tb20">
            	<div class="container">
                    <ul class="wt-breadcrumb breadcrumb-style-2">
                        <li><a href="/"><i class="fa fa-home"></i> Ana Sayfa</a></li>
                        <li>Ürünlerimiz</li>
                    </ul>
                </div>
            </div>
            <!-- BREADCRUMB ROW END -->
            
            <!-- SECTION CONTENT START -->
            <div class="section-full p-t80 p-b50">
                <div class="container">
                    <div class="section-content">
                    	<div class="row">
                            <!-- SIDE BAR START -->
                            <div class="col-md-4">
                                <aside class="side-bar">
                                    <div class="widget bg-white  recent-posts-entry">
                                        <div class="p-b10">
                                            <h2 class="text-uppercase">ÜRÜN KATEGORİLERİ</h2>
                                                <div class="wt-separator-outer m-b30">
                                                    <div class="wt-separator style-square">
                                                        <span class="separator-left bg-primary"></span>
                                                        <span class="separator-right bg-primary"></span>
                                                    </div>
                                                </div>
                                            </div>       
                                            <div class="section-content">
                                               <div class="sidenav">
                                            <a clas="active" href="{% url 'web:per_view' %}" style="background-color:#d2242a;color:#fff;">TÜM ÜRÜNLERİMİZ</a>
                                            
                                            <button class="dropdown-btn active" style="background-color:#d2242a;margin-top: 10px;color:#fff;">DIŞ ORTAM 
                                                <i class="fa fa-caret-down"></i>
                                            </button>
                                            <div class="dropdown-container" style="display:block;">
                                                <a href="{% url 'web:dis_cadde' %}">Cadde Aydınlatması</a>
                                                <a  href="{% url 'web:linner_led' %}">Lineer LedTube Volans</a>
                                                <a href="{% url 'web:dot-led-scorpius' %}">Dot Led Scorpius</a>
                                                <a href="{% url 'web:projector' %}">Projector</a>
                                                <a href="{% url 'web:el-feneri' %}">El Feneri</a>
                                                <a href="{% url 'web:park' %}">Park Bahçe Aydınlatması</a>
                                                <a href="{% url 'web:wallwasher' %}">Wallwasher</a>
                                                <a href="{% url 'web:mobil-isik-kulesi' %}">Mobil Işık Kulesi</a>
                                                <a href="{% url 'web:arac-ustu-isik-kulesi' %}">Araç Üstü Işık Kulesi</a>
                                                <a href="{% url 'web:ufled' %}">Portatif Alan Aydınlatması UFLED</a>
                                                <a href="{% url 'web:ybtsed' %}">Modüler Led Aydınlatma Seti YBT</a>
                                                <a href="{% url 'web:dek-led-ampul' %}">Dekoratif Led Ampül</a>
                                                <a style="color:#d2242a;"  href="{% url 'web:aksesuarlar' %}">Aksesuarlar</a>
                                                
                                            </div>
                                               <button class="dropdown-btn" style="background-color:#d2242a;margin-top: 10px;color:#fff;">İÇ ORTAM 
                                                <i class="fa fa-caret-down"></i>
                                            </button>
                                            <div class="dropdown-container">
                                                <a href="{% url 'web:dek-led-ampul-ic' %}">Dekoratif Led Ampül</a>
                                                <a href="{% url 'web:yuk-tav-led' %}">Yüksek Tavan Led Aydınlatması</a>
                                                <a href="{% url 'web:dek-led-ayd-seti' %}">Dekoratif Led Aydınlatma Seti</a>
                                            </div>
                                               <button class="dropdown-btn" style="background-color:#d2242a;margin-top: 10px;color:#fff;">YARDIMCI ÜRÜNLER
                                                <i class="fa fa-caret-down"></i>
                                            </button>
                                            <div class="dropdown-container">
                                                <a href="{% url 'web:cobled' %}">COB LED Modül Armekeddon</a>
                                                <a href="{% url 'web:waterprof' %}">Waterproof Konnektörler</a>
                                                <a href="{% url 'web:waterprofener' %}">Waterproof Enerji Dağıtıcı</a>
                                            </div>
                                            </div>
                                            </div>
                                   </aside>
                                </div>
                            <!-- SIDE BAR END --> 
                            <div class="col-md-8"> 
                                <!-- TITLE START -->
                                <div class="p-b10">
                                    <h2 class="text-uppercase">Aksesuarlar</h2>
                                    <div class="wt-separator-outer m-b30">
                                        <div class="wt-separator style-square">
                                            <span class="separator-left bg-primary"></span>
                                            <span class="separator-right bg-primary"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <!-- COLUMNS 1 -->
                                    {% for prod in  pro %}
                                    <div class="col-md-4 col-sm-4 col-xs-6 col-xs-100pc m-b30">
                                        <div class="wt-box wt-product-box">
                                            <div class="wt-thum-bx wt-img-overlay1 wt-img-effect zoom">
                                             <a href="{% url 'web:per_detail_view' prod.slug %}">   <img src="{{prod.image.url}}" alt=""></a>
                                            </div>
                                            <div class="wt-info  text-center">
                                                 <div class="p-a10 bg-white">
                                                    <h4 class="wt-title">
                                                        <a href="{% url 'web:per_detail_view' prod.slug %}">{{prod.title}}</a>
                                                    </h4>
                                                    <span class="price">
                                                       
                                                    </span>
                                                    <div class="p-t10">
                                                        <a href="{% url 'web:per_detail_view' prod.slug %}" class="site-button  m-r15" type="button">İncele  
                                                        <i class="fa fa-angle-double-right"></i></a>
                                                    </div>
                                                 </div>
                                            </div>
                                        </div>
                                    </div>
                                   {% endfor %}                            
                                </div>
                            </div>
                            {% include "web/includes/paginate.html" with page_obj=bloglist_tr %}

                       </div> 
                   </div>
                 </div>
             </div>
             <!-- SECTION CONTENT END -->

        </div>
        {% include 'web/includes/contacttr.html' %}

{% endblock content %}
{% block extrajs %}

<script type="text/javascript"  src="{% static  'web/js/aside.js' %}"></script>

{% endblock extrajs %}